/**
 * Pakistan exam, test, job and degree-programme catalogue.
 *
 * This file is the single source of truth for what the platform can prepare a
 * user for. Each exam declares the education levels and subjects that define
 * its syllabus; the Question Selection Engine turns those declarations into a
 * filtered question pool. Nothing here is hard-coded into the UI.
 *
 * `levels` is what makes preparation qualification-aware: a matric-level
 * practice exam and a post-graduation degree exam never share questions that
 * do not belong to their level.
 */

import type { SeedExam } from "../taxonomy";

type ExamType = SeedExam["type"];

interface ExamInput {
  slug: string;
  name: string;
  short?: string;
  description?: string;
  type: ExamType;
  cat: string;
  org?: string;
  prov?: string;
  levels: string[];
  subjects: string[];
  featured?: boolean;
  mode?: "STATIC" | "RANDOM";
  count?: number;
  time?: number;
  neg?: boolean;
  negFactor?: number;
  passing?: number;
  eligibility?: string;
  pattern?: string;
  syllabus?: string;
  duration?: string;
  marks?: string;
  website?: string;
}

let order = 0;
function exam(e: ExamInput): SeedExam {
  order += 1;
  const level = e.levels[0] ?? "graduation";
  return {
    slug: e.slug,
    name: e.name,
    shortName: e.short ?? e.name,
    description:
      e.description ??
      `${e.name} preparation with syllabus-aligned MCQs, practice quizzes and previous papers.`,
    type: e.type,
    province: e.prov,
    isFeatured: e.featured ?? false,
    sortOrder: order,
    educationLevels: e.levels,
    subjects: e.subjects,
    category: e.cat,
    organization: e.org,
    eligibility: e.eligibility,
    testPattern: e.pattern,
    syllabus: e.syllabus,
    duration: e.duration,
    totalMarks: e.marks,
    website: e.website,
    configuration: {
      mode: e.mode ?? "RANDOM",
      defaultQuestionCount: e.count ?? 20,
      timeLimitMinutes: e.time ?? 30,
      negativeMarking: e.neg ?? false,
      negativeMarkFactor: e.negFactor ?? 0,
      marksPerQuestion: 1,
      passingPercentage: e.passing ?? 50,
      staticOrderSeed: e.mode === "STATIC" ? e.slug : undefined,
    },
  };
}

/* Reusable subject bundles ------------------------------------------------- */

const LANG = ["english", "urdu"];
const GK = ["general-knowledge", "pakistan-studies", "islamiat", "everyday-science", "current-affairs"];
const GK_CORE = ["general-knowledge", "pakistan-studies", "islamiat", "everyday-science"];
const TEACH_SUBJECTS = [
  "education",
  "english",
  "urdu",
  "mathematics",
  "islamiat",
  "general-science",
  "pakistan-studies",
  "general-knowledge",
  "computer",
];
const CSS_SUBJECTS = [
  "english",
  "urdu",
  "islamiat",
  "pakistan-affairs",
  "current-affairs-competitive",
  "history",
  "political-science",
  "international-relations",
  "economics",
  "sociology",
  "geography",
  "philosophy",
  "law",
  "general-science",
  "mathematics",
  "computer-science",
  "islamic-studies",
  "psychology",
  "accounting",
  "gender-studies",
];
const SCIENCE_SUBJECTS = ["physics", "chemistry", "biology", "mathematics", "english", "computer"];
const PREMED = ["biology", "chemistry", "physics", "english", "mathematics", "general-knowledge"];
const PREENG = ["mathematics", "physics", "chemistry", "english", "computer", "general-knowledge"];
const COMMERCE_SUBJECTS = ["accounting", "economics", "commerce", "business-administration", "finance", "english", "mathematics", "general-knowledge"];
const IT_SUBJECTS = ["computer", "computer-science", "information-technology", "software-engineering", "english", "mathematics", "general-knowledge"];
const POLICE_SUBJECTS = ["general-knowledge", "pakistan-studies", "islamiat", "english", "urdu", "everyday-science", "analytical-reasoning", "current-affairs"];
const DEFENCE_SUBJECTS = ["general-knowledge", "pakistan-studies", "islamiat", "english", "mathematics", "physics", "everyday-science", "analytical-reasoning"];
const HEALTH_SUBJECTS = ["biology", "anatomy", "physiology", "nursing", "public-health", "biochemistry", "chemistry", "english", "general-knowledge"];
const ENGG_SUBJECTS = ["mathematics", "physics", "chemistry", "english", "computer", "electrical-engineering", "mechanical-engineering", "civil-engineering"];
const AGRICULTURE_SUBJECTS = ["agriculture", "biology", "chemistry", "botany", "zoology", "english", "general-knowledge"];
const LAW_SUBJECTS = ["law", "english", "urdu", "islamiat", "pakistan-studies", "general-knowledge", "political-science", "islamic-studies"];
const MEDIA_SUBJECTS = ["mass-communication", "english", "urdu", "pakistan-studies", "general-knowledge", "current-affairs", "political-science"];
const LANG_MAJOR = (lang: string) => [lang, "english", "urdu", "islamiat", "pakistan-studies", "general-knowledge"];

export const EXAMS: SeedExam[] = [
  /* ===================== Competitive examinations ===================== */
  exam({
    slug: "css",
    name: "CSS (Central Superior Services)",
    short: "CSS",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "fpsc",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    featured: true,
    mode: "RANDOM",
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
    eligibility: "Bachelor's degree (2nd division) from a recognised university.",
    pattern: "MCQ screening + written papers + psychological assessment + viva.",
    duration: "MCQ screening 3 hours",
    website: "https://www.fpsc.gov.pk",
  }),
  exam({
    slug: "pms-punjab",
    name: "PMS Punjab (Provincial Management Service)",
    short: "PMS Punjab",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    featured: true,
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "pms-sindh",
    name: "PMS Sindh (Provincial Management Service)",
    short: "PMS Sindh",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "spsc",
    prov: "Sindh",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "pms-kp",
    name: "PMS Khyber Pakhtunkhwa",
    short: "PMS KP",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "kppsc",
    prov: "Khyber Pakhtunkhwa",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "pms-balochistan",
    name: "PMS Balochistan",
    short: "PMS Balochistan",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "bpsc",
    prov: "Balochistan",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "fpsc-general",
    name: "FPSC General Recruitment Test",
    short: "FPSC",
    type: "COMPETITIVE",
    cat: "government-jobs",
    org: "fpsc",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    featured: true,
    count: 100,
    time: 120,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "ppsc-general",
    name: "PPSC General Recruitment Test",
    short: "PPSC",
    type: "JOB",
    cat: "government-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "spsc-general",
    name: "SPSC General Recruitment Test",
    short: "SPSC",
    type: "JOB",
    cat: "government-jobs",
    org: "spsc",
    prov: "Sindh",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "kppsc-general",
    name: "KPPSC General Recruitment Test",
    short: "KPPSC",
    type: "JOB",
    cat: "government-jobs",
    org: "kppsc",
    prov: "Khyber Pakhtunkhwa",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "bpsc-general",
    name: "BPSC General Recruitment Test",
    short: "BPSC",
    type: "JOB",
    cat: "government-jobs",
    org: "bpsc",
    prov: "Balochistan",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "ajkpsc-general",
    name: "AJK PSC Combined Competitive Exam",
    short: "AJK PSC",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "ajkpsc",
    prov: "Azad Kashmir",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "gbpsc-general",
    name: "GB PSC Combined Competitive Exam",
    short: "GB PSC",
    type: "COMPETITIVE",
    cat: "competitive-exams",
    org: "gbpsc",
    prov: "Gilgit-Baltistan",
    levels: ["graduation"],
    subjects: CSS_SUBJECTS,
    count: 100,
    time: 180,
    neg: true,
    negFactor: 0.25,
  }),
  exam({
    slug: "nts-general",
    name: "NTS General Test",
    short: "NTS",
    type: "JOB",
    cat: "government-jobs",
    org: "nts",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    featured: true,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "ots-general",
    name: "OTS General Test",
    short: "OTS",
    type: "JOB",
    cat: "government-jobs",
    org: "ots",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
  }),
  exam({
    slug: "pts-general",
    name: "PTS General Test",
    short: "PTS",
    type: "JOB",
    cat: "government-jobs",
    org: "pts",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
  }),
  exam({
    slug: "cts-general",
    name: "CTS General Test",
    short: "CTS",
    type: "JOB",
    cat: "government-jobs",
    org: "cts",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 120,
  }),

  /* ===================== Teaching tests ===================== */
  exam({
    slug: "pst",
    name: "PST (Primary School Teacher)",
    short: "PST",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS,
    featured: true,
    mode: "STATIC",
    count: 100,
    time: 90,
    eligibility: "Bachelor's degree with B.Ed / equivalent teaching qualification.",
    pattern: "100 MCQs: subject knowledge, pedagogy, GK, Islamiat, English, Urdu.",
    duration: "1 hour 30 minutes",
    marks: "100",
  }),
  exam({
    slug: "jest",
    name: "JEST (Junior Elementary School Teacher)",
    short: "JEST",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science", "computer"]),
    featured: true,
    count: 100,
    time: 90,
    eligibility: "Bachelor's degree with B.Ed / equivalent.",
  }),
  exam({
    slug: "est",
    name: "EST (Elementary School Teacher)",
    short: "EST",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "sst",
    name: "SST (Secondary School Teacher)",
    short: "SST",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science", "computer-science"]),
    featured: true,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "ss-federal",
    name: "Federal SS (Secondary School Teacher)",
    short: "Federal SS",
    type: "JOB",
    cat: "teaching-tests",
    org: "fpsc",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "aeo",
    name: "AEO (Assistant Education Officer)",
    short: "AEO",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["education", "general-knowledge"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "headmaster",
    name: "Headmaster / Headmistress",
    short: "Headmaster",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["education"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "deputy-headmaster",
    name: "Deputy Headmaster / Deputy Headmistress",
    short: "Dy. Headmaster",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["education"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "educator",
    name: "Educator (School Education Department)",
    short: "Educator",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "lecturer-punjab",
    name: "Lecturer (Punjab Higher Education)",
    short: "Lecturer Punjab",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science", "computer-science", "statistics"]),
    featured: true,
    count: 100,
    time: 90,
    eligibility: "Master's degree in the relevant subject (2nd division).",
  }),
  exam({
    slug: "lecturer-sindh",
    name: "Lecturer (Sindh)",
    short: "Lecturer Sindh",
    type: "JOB",
    cat: "teaching-tests",
    org: "spsc",
    prov: "Sindh",
    levels: ["post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science", "sindhi"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "lecturer-kp",
    name: "Lecturer (Khyber Pakhtunkhwa)",
    short: "Lecturer KP",
    type: "JOB",
    cat: "teaching-tests",
    org: "kppsc",
    prov: "Khyber Pakhtunkhwa",
    levels: ["post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science", "pashto"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "lecturer-balochistan",
    name: "Lecturer (Balochistan)",
    short: "Lecturer Balochistan",
    type: "JOB",
    cat: "teaching-tests",
    org: "bpsc",
    prov: "Balochistan",
    levels: ["post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science", "balochi"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "lecturer-federal",
    name: "Lecturer (Federal / FGEI)",
    short: "Lecturer Federal",
    type: "JOB",
    cat: "teaching-tests",
    org: "fpsc",
    levels: ["post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["general-science"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "professor-college",
    name: "College Professor / Associate Professor",
    short: "Professor",
    type: "JOB",
    cat: "teaching-tests",
    org: "fpsc",
    levels: ["post-graduation", "doctorate"],
    subjects: TEACH_SUBJECTS.concat(["general-science"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "jst-sindh",
    name: "JST (Junior School Teacher, Sindh)",
    short: "JST Sindh",
    type: "JOB",
    cat: "teaching-tests",
    org: "spsc",
    prov: "Sindh",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS.concat(["sindhi"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "hst-sindh",
    name: "HST (High School Teacher, Sindh)",
    short: "HST Sindh",
    type: "JOB",
    cat: "teaching-tests",
    org: "spsc",
    prov: "Sindh",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS.concat(["sindhi"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "pst-sindh",
    name: "PST Sindh (Primary School Teacher)",
    short: "PST Sindh",
    type: "JOB",
    cat: "teaching-tests",
    org: "spsc",
    prov: "Sindh",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS.concat(["sindhi"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "ct-kp",
    name: "CT (Certified Teacher, Khyber Pakhtunkhwa)",
    short: "CT KP",
    type: "JOB",
    cat: "teaching-tests",
    org: "kppsc",
    prov: "Khyber Pakhtunkhwa",
    levels: ["intermediate", "graduation"],
    subjects: TEACH_SUBJECTS.concat(["pashto"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "pst-kp",
    name: "PST Khyber Pakhtunkhwa",
    short: "PST KP",
    type: "JOB",
    cat: "teaching-tests",
    org: "kppsc",
    prov: "Khyber Pakhtunkhwa",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS.concat(["pashto"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "sst-kp",
    name: "SST Khyber Pakhtunkhwa",
    short: "SST KP",
    type: "JOB",
    cat: "teaching-tests",
    org: "kppsc",
    prov: "Khyber Pakhtunkhwa",
    levels: ["graduation", "post-graduation"],
    subjects: TEACH_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "pet",
    name: "PET (Physical Education Teacher)",
    short: "PET",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: ["physical-education", "general-knowledge", "english", "urdu", "islamiat", "pakistan-studies", "everyday-science"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "qari",
    name: "Qari / Quran Teacher",
    short: "Qari",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["matric", "intermediate", "graduation"],
    subjects: ["quran-hadith", "islamiat", "seerah", "urdu", "general-knowledge"],
    count: 100,
    time: 60,
  }),
  exam({
    slug: "drawing-master",
    name: "Drawing Master",
    short: "Drawing Master",
    type: "JOB",
    cat: "teaching-tests",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: ["fine-arts", "general-knowledge", "english", "urdu", "islamiat"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "nts-teaching",
    name: "NTS Teaching Test",
    short: "NTS Teaching",
    type: "JOB",
    cat: "teaching-tests",
    org: "nts",
    levels: ["graduation"],
    subjects: TEACH_SUBJECTS,
    count: 100,
    time: 90,
  }),

  /* ===================== Entry & admission tests ===================== */
  exam({
    slug: "mdcat",
    name: "MDCAT (Medical & Dental College Admission Test)",
    short: "MDCAT",
    type: "ADMISSION",
    cat: "medical-engineering",
    org: "pmc",
    levels: ["intermediate"],
    subjects: PREMED,
    featured: true,
    count: 200,
    time: 210,
    eligibility: "FSc (Pre-Medical) or equivalent with minimum 60%.",
    pattern: "200 MCQs: Biology 80, Chemistry 60, Physics 40, English 20.",
    duration: "3 hours 30 minutes",
    marks: "200",
    website: "https://www.pmdc.pk",
  }),
  exam({
    slug: "ecat",
    name: "ECAT (Engineering College Admission Test)",
    short: "ECAT",
    type: "ADMISSION",
    cat: "medical-engineering",
    org: "uet",
    levels: ["intermediate"],
    subjects: PREENG,
    featured: true,
    count: 100,
    time: 120,
    eligibility: "FSc (Pre-Engineering) or equivalent.",
    pattern: "100 MCQs: Maths, Physics, Chemistry, English.",
  }),
  exam({
    slug: "nat-im",
    name: "NAT-IM (NTS National Aptitude Test — Pre-Medical)",
    short: "NAT-IM",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["intermediate"],
    subjects: PREMED,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "nat-ie",
    name: "NAT-IE (NTS National Aptitude Test — Pre-Engineering)",
    short: "NAT-IE",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["intermediate"],
    subjects: PREENG,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "nat-ics",
    name: "NAT-ICS (NTS National Aptitude Test — Computer Science)",
    short: "NAT-ICS",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["intermediate"],
    subjects: ["mathematics", "physics", "computer", "english", "general-knowledge"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "nat-icom",
    name: "NAT-ICOM (NTS National Aptitude Test — Commerce)",
    short: "NAT-ICOM",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["intermediate"],
    subjects: COMMERCE_SUBJECTS,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "nat-ia",
    name: "NAT-IA (NTS National Aptitude Test — Arts & Humanities)",
    short: "NAT-IA",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["intermediate"],
    subjects: ["english", "urdu", "islamiat", "pakistan-studies", "general-knowledge", "history", "geography", "civics"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "gat-general",
    name: "GAT General (NTS Graduate Assessment Test)",
    short: "GAT General",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["graduation"],
    subjects: ["english", "analytical-reasoning", "mathematics", "general-knowledge", "pakistan-studies", "islamiat"],
    featured: true,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "gat-subject",
    name: "GAT Subject",
    short: "GAT Subject",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nts",
    levels: ["post-graduation"],
    subjects: ["english", "analytical-reasoning", "general-knowledge", "mathematics", "computer-science", "statistics"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "hat",
    name: "HAT (HEC Aptitude Test)",
    short: "HAT",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "hec",
    levels: ["post-graduation", "doctorate"],
    subjects: ["english", "analytical-reasoning", "general-knowledge", "research-methods"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "usat",
    name: "USAT (Undergraduate Studies Admission Test)",
    short: "USAT",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "hec",
    levels: ["intermediate"],
    subjects: ["english", "mathematics", "analytical-reasoning", "general-knowledge", "physics", "chemistry", "biology"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "lat",
    name: "LAT (Law Admission Test)",
    short: "LAT",
    type: "ADMISSION",
    cat: "judicial-legal",
    org: "hec",
    levels: ["intermediate", "graduation"],
    subjects: LAW_SUBJECTS.concat(["analytical-reasoning"]),
    count: 100,
    time: 120,
  }),
  exam({
    slug: "nust-net",
    name: "NUST Entry Test (NET)",
    short: "NUST NET",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "nust",
    levels: ["intermediate"],
    subjects: PREENG.concat(["analytical-reasoning", "english"]),
    count: 100,
    time: 120,
  }),
  exam({
    slug: "fast-entry",
    name: "FAST University Entry Test",
    short: "FAST Entry",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "fast",
    levels: ["intermediate"],
    subjects: PREENG.concat(["analytical-reasoning"]),
    count: 100,
    time: 120,
  }),
  exam({
    slug: "ned-entry",
    name: "NED University Entry Test",
    short: "NED Entry",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "ned",
    levels: ["intermediate"],
    subjects: PREENG,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "uet-entry",
    name: "UET Entry Test",
    short: "UET Entry",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "uet",
    levels: ["intermediate"],
    subjects: PREENG,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "giki-entry",
    name: "GIKI Entry Test",
    short: "GIKI Entry",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "giki",
    levels: ["intermediate"],
    subjects: PREENG.concat(["analytical-reasoning"]),
    count: 100,
    time: 120,
  }),
  exam({
    slug: "aku-entry",
    name: "AKU Entry Test (Medical)",
    short: "AKU Entry",
    type: "ADMISSION",
    cat: "medical-engineering",
    org: "aku",
    levels: ["intermediate"],
    subjects: PREMED,
    count: 100,
    time: 150,
  }),
  exam({
    slug: "uhs-entry",
    name: "UHS Entry Test",
    short: "UHS Entry",
    type: "ADMISSION",
    cat: "medical-engineering",
    org: "uhs",
    prov: "Punjab",
    levels: ["intermediate"],
    subjects: PREMED,
    count: 200,
    time: 210,
  }),
  exam({
    slug: "bs-admission",
    name: "BS Programme Admission Test",
    short: "BS Admission",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "hec",
    levels: ["intermediate"],
    subjects: ["english", "mathematics", "analytical-reasoning", "general-knowledge", "computer"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "mphil-admission",
    name: "MPhil / MS Admission Test",
    short: "MPhil Admission",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "hec",
    levels: ["post-graduation"],
    subjects: ["english", "analytical-reasoning", "general-knowledge", "research-methods"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "phd-admission",
    name: "PhD Admission Test",
    short: "PhD Admission",
    type: "ADMISSION",
    cat: "entry-tests",
    org: "hec",
    levels: ["post-graduation", "doctorate"],
    subjects: ["english", "analytical-reasoning", "research-methods", "general-knowledge"],
    count: 100,
    time: 120,
  }),

  /* ===================== Academic / board exams ===================== */
  exam({
    slug: "matric-ssc",
    name: "Matric / SSC (Class 9–10)",
    short: "Matric",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["matric"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "urdu", "islamiat", "pakistan-studies", "computer", "general-science"],
    featured: true,
    mode: "STATIC",
    count: 50,
    time: 60,
  }),
  exam({
    slug: "intermediate-hssc",
    name: "Intermediate / HSSC (Class 11–12)",
    short: "Intermediate",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["intermediate"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "urdu", "islamiat", "pakistan-studies", "computer", "economics", "accounting"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "o-level",
    name: "O-Level",
    short: "O-Level",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["matric"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "computer", "economics", "accounting", "geography", "history"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "a-level",
    name: "A-Level",
    short: "A-Level",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["intermediate"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "computer-science", "economics", "accounting", "psychology", "history"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "class-9-practice",
    name: "Class 9 Subject Practice",
    short: "Class 9",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["matric"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "urdu", "islamiat", "pakistan-studies", "computer"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "class-10-practice",
    name: "Class 10 Subject Practice",
    short: "Class 10",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["matric"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "urdu", "islamiat", "pakistan-studies", "computer"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "class-11-practice",
    name: "Class 11 Subject Practice",
    short: "Class 11",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["intermediate"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "urdu", "islamiat", "pakistan-studies", "computer"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "class-12-practice",
    name: "Class 12 Subject Practice",
    short: "Class 12",
    type: "EDUCATIONAL",
    cat: "academic-exams",
    levels: ["intermediate"],
    subjects: ["mathematics", "physics", "chemistry", "biology", "english", "urdu", "islamiat", "pakistan-studies", "computer"],
    count: 50,
    time: 60,
  }),

  /* ===================== Government jobs ===================== */
  exam({
    slug: "police-punjab",
    name: "Punjab Police Recruitment Test",
    short: "Punjab Police",
    type: "JOB",
    cat: "police-armed-forces",
    org: "punjab-police",
    prov: "Punjab",
    levels: ["matric", "intermediate", "graduation"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "police-sindh",
    name: "Sindh Police Recruitment Test",
    short: "Sindh Police",
    type: "JOB",
    cat: "police-armed-forces",
    org: "sindh-police",
    prov: "Sindh",
    levels: ["matric", "intermediate", "graduation"],
    subjects: POLICE_SUBJECTS.concat(["sindhi"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "police-kp",
    name: "Khyber Pakhtunkhwa Police Recruitment Test",
    short: "KP Police",
    type: "JOB",
    cat: "police-armed-forces",
    org: "kp-police",
    prov: "Khyber Pakhtunkhwa",
    levels: ["matric", "intermediate", "graduation"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "police-balochistan",
    name: "Balochistan Police Recruitment Test",
    short: "Balochistan Police",
    type: "JOB",
    cat: "police-armed-forces",
    org: "balochistan-police",
    prov: "Balochistan",
    levels: ["matric", "intermediate", "graduation"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "asi",
    name: "ASI (Assistant Sub-Inspector)",
    short: "ASI",
    type: "JOB",
    cat: "police-armed-forces",
    org: "punjab-police",
    prov: "Punjab",
    levels: ["intermediate", "graduation"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "si-police",
    name: "SI (Sub-Inspector) Police",
    short: "SI Police",
    type: "JOB",
    cat: "police-armed-forces",
    org: "punjab-police",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "army-pma",
    name: "Pakistan Army (PMA Long Course)",
    short: "Army PMA",
    type: "JOB",
    cat: "police-armed-forces",
    org: "pak-army",
    levels: ["intermediate", "graduation"],
    subjects: DEFENCE_SUBJECTS,
    featured: true,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "paf-gd-pilot",
    name: "PAF GD Pilot",
    short: "PAF GD Pilot",
    type: "JOB",
    cat: "police-armed-forces",
    org: "paf",
    levels: ["intermediate", "graduation"],
    subjects: DEFENCE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "paf-aeronautical",
    name: "PAF Aeronautical Engineering",
    short: "PAF Aeronautical",
    type: "JOB",
    cat: "police-armed-forces",
    org: "paf",
    levels: ["intermediate", "graduation"],
    subjects: DEFENCE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "navy",
    name: "Pakistan Navy Recruitment",
    short: "Navy",
    type: "JOB",
    cat: "police-armed-forces",
    org: "pak-navy",
    levels: ["intermediate", "graduation"],
    subjects: DEFENCE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "fc",
    name: "Frontier Corps Recruitment",
    short: "FC",
    type: "JOB",
    cat: "police-armed-forces",
    org: "fc",
    levels: ["matric", "intermediate"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "rangers",
    name: "Rangers Recruitment",
    short: "Rangers",
    type: "JOB",
    cat: "police-armed-forces",
    org: "rangers",
    levels: ["matric", "intermediate"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "asf",
    name: "Airport Security Force (ASF)",
    short: "ASF",
    type: "JOB",
    cat: "police-armed-forces",
    org: "asf",
    levels: ["matric", "intermediate"],
    subjects: POLICE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "fia",
    name: "FIA Recruitment Test",
    short: "FIA",
    type: "JOB",
    cat: "government-jobs",
    org: "fia",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "computer"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "ib",
    name: "Intelligence Bureau (IB)",
    short: "IB",
    type: "JOB",
    cat: "government-jobs",
    org: "ib",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "nab",
    name: "NAB Recruitment Test",
    short: "NAB",
    type: "JOB",
    cat: "government-jobs",
    org: "nab",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "analytical-reasoning", "law"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "customs",
    name: "Pakistan Customs Recruitment",
    short: "Customs",
    type: "JOB",
    cat: "government-jobs",
    org: "fbr",
    levels: ["graduation"],
    subjects: GK.concat(["english", "mathematics", "accounting", "economics", "law"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "income-tax",
    name: "Income Tax Officer Recruitment",
    short: "Income Tax",
    type: "JOB",
    cat: "government-jobs",
    org: "fbr",
    levels: ["graduation"],
    subjects: GK.concat(["english", "accounting", "economics", "mathematics", "law"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "railway",
    name: "Pakistan Railways Recruitment",
    short: "Railway",
    type: "JOB",
    cat: "government-jobs",
    org: "pak-railways",
    levels: ["matric", "intermediate", "graduation"],
    subjects: GK_CORE.concat(["english", "urdu", "mathematics", "analytical-reasoning"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "wapda",
    name: "WAPDA Recruitment Test",
    short: "WAPDA",
    type: "JOB",
    cat: "government-jobs",
    org: "wapda",
    levels: ["intermediate", "graduation"],
    subjects: GK.concat(["english", "mathematics", "physics", "electrical-engineering"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "nadra",
    name: "NADRA Recruitment Test",
    short: "NADRA",
    type: "JOB",
    cat: "government-jobs",
    org: "nadra",
    levels: ["intermediate", "graduation"],
    subjects: GK.concat(["english", "mathematics", "computer", "analytical-reasoning"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "health-dept-jobs",
    name: "Health Department Jobs (Punjab)",
    short: "Health Dept",
    type: "JOB",
    cat: "health-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["intermediate", "graduation"],
    subjects: HEALTH_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "charge-nurse",
    name: "Charge Nurse Recruitment",
    short: "Charge Nurse",
    type: "JOB",
    cat: "health-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: ["nursing", "biology", "anatomy", "physiology", "public-health", "english", "general-knowledge"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "dispenser",
    name: "Dispenser / Pharmacist Recruitment",
    short: "Dispenser",
    type: "JOB",
    cat: "health-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["intermediate", "graduation"],
    subjects: ["pharmacology", "chemistry", "biology", "general-knowledge", "english"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "lab-technician",
    name: "Lab Technician Recruitment",
    short: "Lab Technician",
    type: "JOB",
    cat: "health-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["intermediate", "graduation"],
    subjects: ["biology", "chemistry", "biochemistry", "medical", "general-knowledge", "english"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "agriculture-jobs",
    name: "Agriculture Department Jobs",
    short: "Agriculture Jobs",
    type: "JOB",
    cat: "government-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation", "post-graduation"],
    subjects: AGRICULTURE_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "it-jobs",
    name: "IT / Computer Jobs Test",
    short: "IT Jobs",
    type: "JOB",
    cat: "it-computer-jobs",
    org: "nts",
    levels: ["graduation"],
    subjects: IT_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "data-entry-operator",
    name: "Data Entry Operator Test",
    short: "Data Entry",
    type: "JOB",
    cat: "it-computer-jobs",
    org: "nts",
    levels: ["intermediate", "graduation"],
    subjects: ["computer", "information-technology", "english", "mathematics", "general-knowledge"],
    count: 100,
    time: 60,
  }),
  exam({
    slug: "computer-operator",
    name: "Computer Operator Test",
    short: "Computer Operator",
    type: "JOB",
    cat: "it-computer-jobs",
    org: "nts",
    levels: ["intermediate", "graduation"],
    subjects: ["computer", "information-technology", "english", "general-knowledge"],
    count: 100,
    time: 60,
  }),
  exam({
    slug: "press-information",
    name: "Press Information Department Jobs",
    short: "Press Info",
    type: "JOB",
    cat: "media-jobs",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: MEDIA_SUBJECTS,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "radio-pakistan",
    name: "Radio Pakistan Recruitment",
    short: "Radio Pakistan",
    type: "JOB",
    cat: "media-jobs",
    org: "radio-pakistan",
    levels: ["graduation"],
    subjects: MEDIA_SUBJECTS,
    count: 100,
    time: 90,
  }),

  /* ===================== Banking & finance ===================== */
  exam({
    slug: "sbp",
    name: "State Bank of Pakistan (SBP) Test",
    short: "SBP",
    type: "JOB",
    cat: "banking-tests",
    org: "sbp",
    levels: ["graduation", "post-graduation"],
    subjects: COMMERCE_SUBJECTS.concat(["banking", "english", "analytical-reasoning"]),
    featured: true,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "bank-general",
    name: "Banking Sector General Test",
    short: "Bank Test",
    type: "JOB",
    cat: "banking-tests",
    org: "ibp",
    levels: ["graduation"],
    subjects: COMMERCE_SUBJECTS.concat(["banking", "english", "analytical-reasoning"]),
    featured: true,
    count: 100,
    time: 90,
  }),
  exam({
    slug: "nbp",
    name: "National Bank of Pakistan (NBP) Test",
    short: "NBP",
    type: "JOB",
    cat: "banking-tests",
    org: "nbp",
    levels: ["graduation"],
    subjects: COMMERCE_SUBJECTS.concat(["banking", "english", "analytical-reasoning"]),
    count: 100,
    time: 90,
  }),
  exam({
    slug: "ibp-test",
    name: "Institute of Bankers Pakistan (IBP) Test",
    short: "IBP",
    type: "PROFESSIONAL",
    cat: "banking-tests",
    org: "ibp",
    levels: ["graduation"],
    subjects: COMMERCE_SUBJECTS.concat(["banking", "english"]),
    count: 100,
    time: 90,
  }),

  /* ===================== Technical & diploma ===================== */
  exam({
    slug: "dae",
    name: "DAE (Diploma of Associate Engineering) Entry",
    short: "DAE",
    type: "ADMISSION",
    cat: "technical-diploma",
    org: "tevt",
    levels: ["matric"],
    subjects: ["mathematics", "physics", "chemistry", "english", "general-science", "computer", "engineering-fundamentals"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "dae-electrical",
    name: "DAE Electrical Technology",
    short: "DAE Electrical",
    type: "EDUCATIONAL",
    cat: "technical-diploma",
    org: "tevt",
    levels: ["intermediate", "graduation"],
    subjects: ["electrical-engineering", "electronics", "physics", "mathematics", "english"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "dae-mechanical",
    name: "DAE Mechanical Technology",
    short: "DAE Mechanical",
    type: "EDUCATIONAL",
    cat: "technical-diploma",
    org: "tevt",
    levels: ["intermediate", "graduation"],
    subjects: ["mechanical-engineering", "physics", "mathematics", "english"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "dae-civil",
    name: "DAE Civil Technology",
    short: "DAE Civil",
    type: "EDUCATIONAL",
    cat: "technical-diploma",
    org: "tevt",
    levels: ["intermediate", "graduation"],
    subjects: ["civil-engineering", "physics", "mathematics", "english"],
    count: 100,
    time: 90,
  }),
  exam({
    slug: "dae-computer",
    name: "DAE Computer Information Technology",
    short: "DAE Computer",
    type: "EDUCATIONAL",
    cat: "technical-diploma",
    org: "tevt",
    levels: ["intermediate", "graduation"],
    subjects: ["computer", "information-technology", "computer-science", "mathematics", "english"],
    count: 100,
    time: 90,
  }),

  /* ===================== Professional certification ===================== */
  exam({
    slug: "icap-ca",
    name: "ICAP Chartered Accountancy (CA)",
    short: "ICAP CA",
    type: "PROFESSIONAL",
    cat: "professional-certification",
    org: "icap",
    levels: ["intermediate", "graduation"],
    subjects: ["accounting", "finance", "economics", "commerce", "business-administration", "english", "law", "mathematics"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "icma-cma",
    name: "ICMA Cost & Management Accountancy (CMA)",
    short: "ICMA CMA",
    type: "PROFESSIONAL",
    cat: "professional-certification",
    org: "icma",
    levels: ["intermediate", "graduation"],
    subjects: ["accounting", "finance", "economics", "business-administration", "english", "mathematics"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "acca",
    name: "ACCA",
    short: "ACCA",
    type: "PROFESSIONAL",
    cat: "professional-certification",
    org: "acca",
    levels: ["intermediate", "graduation"],
    subjects: ["accounting", "finance", "business-administration", "economics", "law", "english", "mathematics"],
    count: 100,
    time: 120,
  }),
  exam({
    slug: "pleb",
    name: "Punjab Bar / Legal Practice Test",
    short: "PLEB",
    type: "PROFESSIONAL",
    cat: "judicial-legal",
    org: "pleb",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: LAW_SUBJECTS,
    count: 100,
    time: 120,
  }),
  exam({
    slug: "judicial-service",
    name: "Judicial Service Exam (Civil Judge)",
    short: "Judicial Service",
    type: "COMPETITIVE",
    cat: "judicial-legal",
    org: "ppsc",
    prov: "Punjab",
    levels: ["graduation"],
    subjects: LAW_SUBJECTS.concat(["jurisprudence", "analytical-reasoning"]),
    count: 100,
    time: 180,
  }),
  exam({
    slug: "pmp",
    name: "PMP / Project Management Test",
    short: "PMP",
    type: "PROFESSIONAL",
    cat: "professional-certification",
    org: "pmi",
    levels: ["graduation", "post-graduation"],
    subjects: ["business-administration", "information-technology", "english", "mathematics"],
    count: 100,
    time: 120,
  }),

  /* ===================== Language proficiency ===================== */
  exam({
    slug: "ielts",
    name: "IELTS Preparation",
    short: "IELTS",
    type: "GENERAL",
    cat: "language-tests",
    levels: ["intermediate", "graduation", "post-graduation"],
    subjects: ["english", "english-literature"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "toefl",
    name: "TOEFL Preparation",
    short: "TOEFL",
    type: "GENERAL",
    cat: "language-tests",
    levels: ["intermediate", "graduation", "post-graduation"],
    subjects: ["english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "gre",
    name: "GRE Preparation",
    short: "GRE",
    type: "ADMISSION",
    cat: "language-tests",
    levels: ["graduation", "post-graduation"],
    subjects: ["english", "mathematics", "analytical-reasoning"],
    count: 50,
    time: 90,
  }),
  exam({
    slug: "urdu-proficiency",
    name: "Urdu Language Proficiency",
    short: "Urdu Proficiency",
    type: "GENERAL",
    cat: "language-tests",
    levels: ["intermediate", "graduation", "post-graduation"],
    subjects: LANG_MAJOR("urdu").concat(["urdu-literature"]),
    count: 50,
    time: 60,
  }),
  exam({
    slug: "sindhi-proficiency",
    name: "Sindhi Language Proficiency",
    short: "Sindhi Proficiency",
    type: "GENERAL",
    cat: "language-tests",
    levels: ["intermediate", "graduation", "post-graduation"],
    subjects: LANG_MAJOR("sindhi").concat(["sindhi-literature"]),
    count: 50,
    time: 60,
  }),
  exam({
    slug: "arabic-proficiency",
    name: "Arabic Language Proficiency",
    short: "Arabic Proficiency",
    type: "GENERAL",
    cat: "language-tests",
    levels: ["intermediate", "graduation", "post-graduation"],
    subjects: LANG_MAJOR("arabic"),
    count: 50,
    time: 60,
  }),
  exam({
    slug: "persian-proficiency",
    name: "Persian Language Proficiency",
    short: "Persian Proficiency",
    type: "GENERAL",
    cat: "language-tests",
    levels: ["intermediate", "graduation", "post-graduation"],
    subjects: LANG_MAJOR("persian"),
    count: 50,
    time: 60,
  }),

  /* ===================== Degree programmes (MA / MSc / BS) ============ */
  exam({
    slug: "ma-urdu",
    name: "MA Urdu",
    short: "MA Urdu",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["urdu", "urdu-literature", "english", "islamiat", "pakistan-studies", "general-knowledge"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-sindhi",
    name: "MA Sindhi",
    short: "MA Sindhi",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["sindhi", "sindhi-literature", "english", "urdu", "islamiat", "pakistan-studies"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-english",
    name: "MA English",
    short: "MA English",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["english", "english-literature", "urdu", "islamiat", "pakistan-studies"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-islamiat",
    name: "MA Islamiat",
    short: "MA Islamiat",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["islamiat", "islamic-studies", "seerah", "quran-hadith", "fiqh", "arabic", "english", "urdu"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-islamic-studies",
    name: "MA Islamic Studies",
    short: "MA Islamic Studies",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["islamic-studies", "islamiat", "quran-hadith", "fiqh", "seerah", "arabic", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-pakistan-studies",
    name: "MA Pakistan Studies",
    short: "MA Pak Studies",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["pakistan-studies", "pakistan-affairs", "history", "political-science", "geography", "english", "urdu", "islamiat"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-political-science",
    name: "MA Political Science",
    short: "MA Pol. Science",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["political-science", "international-relations", "history", "sociology", "pakistan-studies", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-international-relations",
    name: "MA International Relations",
    short: "MA IR",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["international-relations", "political-science", "history", "current-affairs-competitive", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-history",
    name: "MA History",
    short: "MA History",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["history", "pakistan-studies", "islamic-studies", "political-science", "english", "urdu"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-economics",
    name: "MA Economics",
    short: "MA Economics",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["economics", "statistics", "mathematics", "finance", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-sociology",
    name: "MA Sociology",
    short: "MA Sociology",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["sociology", "social-work", "psychology", "gender-studies", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-psychology",
    name: "MA Psychology",
    short: "MA Psychology",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["psychology", "sociology", "education", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-education",
    name: "MA Education",
    short: "MA Education",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["education", "psychology", "sociology", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-journalism",
    name: "MA Journalism / Mass Communication",
    short: "MA Journalism",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["mass-communication", "english", "urdu", "political-science", "pakistan-studies", "current-affairs-competitive"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-arabic",
    name: "MA Arabic",
    short: "MA Arabic",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["arabic", "islamic-studies", "islamiat", "english", "urdu"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-persian",
    name: "MA Persian",
    short: "MA Persian",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["persian", "islamic-studies", "english", "urdu", "history"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-punjabi",
    name: "MA Punjabi",
    short: "MA Punjabi",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["punjabi", "english", "urdu", "pakistan-studies", "islamiat"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-pashto",
    name: "MA Pashto",
    short: "MA Pashto",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["pashto", "english", "urdu", "pakistan-studies", "islamiat"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-balochi",
    name: "MA Balochi",
    short: "MA Balochi",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["balochi", "english", "urdu", "pakistan-studies", "islamiat"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-saraiki",
    name: "MA Saraiki",
    short: "MA Saraiki",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["saraiki", "english", "urdu", "pakistan-studies", "islamiat"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-philosophy",
    name: "MA Philosophy",
    short: "MA Philosophy",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["philosophy", "islamic-studies", "history", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-library-science",
    name: "MA Library & Information Science",
    short: "MA LIS",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["library-science", "information-technology", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-gender-studies",
    name: "MA Gender Studies",
    short: "MA Gender Studies",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["gender-studies", "sociology", "social-work", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-social-work",
    name: "MA Social Work",
    short: "MA Social Work",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["social-work", "sociology", "psychology", "public-health", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-fine-arts",
    name: "MA Fine Arts",
    short: "MA Fine Arts",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["fine-arts", "history", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ma-physical-education",
    name: "MA Physical Education",
    short: "MA Phys. Ed",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["physical-education", "biology", "psychology", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-physics",
    name: "MSc Physics",
    short: "MSc Physics",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["physics", "mathematics", "chemistry", "english", "general-knowledge"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-chemistry",
    name: "MSc Chemistry",
    short: "MSc Chemistry",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["chemistry", "physics", "biology", "mathematics", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-biology",
    name: "MSc Biology",
    short: "MSc Biology",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["biology", "chemistry", "zoology", "botany", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-zoology",
    name: "MSc Zoology",
    short: "MSc Zoology",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["zoology", "biology", "chemistry", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-botany",
    name: "MSc Botany",
    short: "MSc Botany",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["botany", "biology", "chemistry", "agriculture", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-mathematics",
    name: "MSc Mathematics",
    short: "MSc Maths",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["mathematics", "statistics", "physics", "english", "computer-science"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-statistics",
    name: "MSc Statistics",
    short: "MSc Statistics",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["statistics", "mathematics", "economics", "english", "computer-science"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-computer-science",
    name: "MSc Computer Science",
    short: "MSc CS",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["computer-science", "mathematics", "information-technology", "english", "general-knowledge"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "msc-psychology",
    name: "MSc Psychology",
    short: "MSc Psychology",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["psychology", "sociology", "biology", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-computer-science",
    name: "BS Computer Science",
    short: "BS CS",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["computer-science", "mathematics", "information-technology", "software-engineering", "english", "physics"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-information-technology",
    name: "BS Information Technology",
    short: "BS IT",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["information-technology", "computer", "computer-science", "mathematics", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-physics",
    name: "BS Physics",
    short: "BS Physics",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["physics", "mathematics", "chemistry", "english", "computer"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-chemistry",
    name: "BS Chemistry",
    short: "BS Chemistry",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["chemistry", "physics", "biology", "mathematics", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-biology",
    name: "BS Biology",
    short: "BS Biology",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["biology", "chemistry", "zoology", "botany", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-mathematics",
    name: "BS Mathematics",
    short: "BS Maths",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["mathematics", "statistics", "physics", "english", "computer"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-english",
    name: "BS English",
    short: "BS English",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["english", "english-literature", "urdu", "islamiat", "pakistan-studies"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "ba-bsc-general",
    name: "BA / BSc General",
    short: "BA/BSc",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["english", "urdu", "islamiat", "pakistan-studies", "general-knowledge", "mathematics", "physics", "chemistry", "biology", "economics", "civics", "history", "geography"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bcom",
    name: "B.Com",
    short: "B.Com",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: COMMERCE_SUBJECTS,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bba",
    name: "BBA",
    short: "BBA",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["business-administration", "accounting", "economics", "finance", "english", "mathematics", "general-knowledge"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "mba",
    name: "MBA",
    short: "MBA",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["business-administration", "accounting", "economics", "finance", "marketing", "english", "general-knowledge"],
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "mcom",
    name: "M.Com",
    short: "M.Com",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: COMMERCE_SUBJECTS,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "llb",
    name: "LLB",
    short: "LLB",
    type: "EDUCATIONAL",
    cat: "judicial-legal",
    levels: ["graduation"],
    subjects: LAW_SUBJECTS,
    featured: true,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "llm",
    name: "LLM",
    short: "LLM",
    type: "EDUCATIONAL",
    cat: "judicial-legal",
    levels: ["post-graduation"],
    subjects: LAW_SUBJECTS.concat(["jurisprudence"]),
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bed",
    name: "B.Ed",
    short: "B.Ed",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ["education", "psychology", "english", "urdu", "islamiat", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "med",
    name: "M.Ed",
    short: "M.Ed",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation"],
    subjects: ["education", "psychology", "sociology", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "pharm-d",
    name: "Pharm-D",
    short: "Pharm-D",
    type: "EDUCATIONAL",
    cat: "health-jobs",
    levels: ["graduation"],
    subjects: ["pharmacology", "chemistry", "biology", "biochemistry", "anatomy", "physiology", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "dpt",
    name: "DPT (Doctor of Physical Therapy)",
    short: "DPT",
    type: "EDUCATIONAL",
    cat: "health-jobs",
    levels: ["graduation"],
    subjects: ["anatomy", "physiology", "biology", "biochemistry", "english", "general-knowledge"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "dvm",
    name: "DVM (Doctor of Veterinary Medicine)",
    short: "DVM",
    type: "EDUCATIONAL",
    cat: "health-jobs",
    levels: ["graduation"],
    subjects: ["zoology", "biology", "chemistry", "agriculture", "anatomy", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bsn",
    name: "BSN (BS Nursing)",
    short: "BSN",
    type: "EDUCATIONAL",
    cat: "health-jobs",
    levels: ["graduation"],
    subjects: ["nursing", "anatomy", "physiology", "biology", "public-health", "english"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-agriculture",
    name: "BS Agriculture",
    short: "BS Agriculture",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: AGRICULTURE_SUBJECTS,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "bs-engineering",
    name: "BS Engineering",
    short: "BS Engineering",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["graduation"],
    subjects: ENGG_SUBJECTS,
    count: 50,
    time: 60,
  }),
  exam({
    slug: "mphil-urdu",
    name: "MPhil Urdu",
    short: "MPhil Urdu",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation", "doctorate"],
    subjects: ["urdu", "urdu-literature", "english", "research-methods"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "mphil-sindhi",
    name: "MPhil Sindhi",
    short: "MPhil Sindhi",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["post-graduation", "doctorate"],
    subjects: ["sindhi", "sindhi-literature", "english", "research-methods"],
    count: 50,
    time: 60,
  }),
  exam({
    slug: "phd-research",
    name: "PhD / Research Programme",
    short: "PhD",
    type: "EDUCATIONAL",
    cat: "degree-programs",
    levels: ["doctorate"],
    subjects: ["english", "research-methods", "general-knowledge", "computer-science", "statistics"],
    count: 50,
    time: 60,
  }),

  /* ===================== General practice ===================== */
  exam({
    slug: "general-knowledge-practice",
    name: "General Knowledge Practice",
    short: "GK Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["primary", "middle", "matric", "intermediate", "graduation", "post-graduation"],
    subjects: ["general-knowledge", "pakistan-studies", "islamiat", "everyday-science", "current-affairs", "geography", "history"],
    featured: true,
    count: 20,
    time: 30,
  }),
  exam({
    slug: "english-grammar",
    name: "English Grammar Practice",
    short: "English Grammar",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["middle", "matric", "intermediate", "graduation", "post-graduation"],
    subjects: ["english"],
    featured: true,
    mode: "RANDOM",
    count: 20,
    time: 30,
  }),
  exam({
    slug: "urdu-grammar",
    name: "Urdu Grammar Practice",
    short: "Urdu Grammar",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["middle", "matric", "intermediate", "graduation", "post-graduation"],
    subjects: ["urdu"],
    featured: true,
    count: 20,
    time: 30,
  }),
  exam({
    slug: "sindhi-practice",
    name: "Sindhi Practice",
    short: "Sindhi Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["primary", "middle", "matric", "intermediate", "graduation"],
    subjects: ["sindhi", "sindhi-literature"],
    count: 20,
    time: 30,
  }),
  exam({
    slug: "mathematics-practice",
    name: "Mathematics Practice",
    short: "Maths Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["primary", "middle", "matric", "intermediate", "graduation"],
    subjects: ["mathematics"],
    count: 20,
    time: 30,
  }),
  exam({
    slug: "computer-practice",
    name: "Computer Practice",
    short: "Computer Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["middle", "matric", "intermediate", "graduation"],
    subjects: ["computer", "computer-science", "information-technology"],
    count: 20,
    time: 30,
  }),
  exam({
    slug: "islamiat-practice",
    name: "Islamiat Practice",
    short: "Islamiat Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["primary", "middle", "matric", "intermediate", "graduation"],
    subjects: ["islamiat", "islamic-studies", "seerah", "quran-hadith"],
    count: 20,
    time: 30,
  }),
  exam({
    slug: "science-practice",
    name: "Science Practice",
    short: "Science Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["primary", "middle", "matric", "intermediate", "graduation"],
    subjects: ["general-science", "everyday-science", "physics", "chemistry", "biology"],
    count: 20,
    time: 30,
  }),
  exam({
    slug: "analytical-reasoning-practice",
    name: "Analytical Reasoning Practice",
    short: "Reasoning Practice",
    type: "GENERAL",
    cat: "general-practice",
    levels: ["matric", "intermediate", "graduation", "post-graduation"],
    subjects: ["analytical-reasoning"],
    count: 20,
    time: 30,
  }),
];
