import type { SeedQuestion } from "../types";

/**
 * Curated original practice questions.
 *
 * These are hand-authored practice items (not previous-paper questions). They
 * complement the algorithmic generators and carry the same metadata so the
 * Question Selection Engine treats them identically. Verified previous-paper
 * questions are imported separately with real source, reference and year.
 */

type BankItem = Omit<
  SeedQuestion,
  "slug" | "exams" | "status" | "origin" | "source"
> & { difficulty: "EASY" | "MEDIUM" | "HARD" };

const BANK: BankItem[] = [
  {
    stem: "Choose the correct plural form of 'child'.",
    subject: "english",
    topic: "parts-of-speech",
    difficulty: "EASY",
    correct: 1,
    options: ["childs", "children", "childes", "childrens"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["english", "grammar", "plural"],
  },
  {
    stem: "Choose the correct article: He is ___ honest man.",
    subject: "english",
    topic: "articles",
    difficulty: "EASY",
    correct: 1,
    options: ["a", "an", "the", "no article"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["english", "articles"],
  },
  {
    stem: "Choose the correct preposition: She is good ___ mathematics.",
    subject: "english",
    topic: "prepositions",
    difficulty: "EASY",
    correct: 1,
    options: ["in", "at", "on", "for"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["english", "prepositions"],
  },
  {
    stem: "Choose the synonym of 'rapid'.",
    subject: "english",
    topic: "synonyms-antonyms",
    difficulty: "EASY",
    correct: 1,
    options: ["slow", "quick", "weak", "late"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["english", "vocabulary"],
  },
  {
    stem: "Choose the antonym of 'ancient'.",
    subject: "english",
    topic: "synonyms-antonyms",
    difficulty: "EASY",
    correct: 2,
    options: ["old", "historic", "modern", "former"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["english", "vocabulary"],
  },
  {
    stem: "Identify the tense: 'She has completed her work.'",
    subject: "english",
    topic: "tenses",
    difficulty: "MEDIUM",
    correct: 2,
    options: ["Present simple", "Present continuous", "Present perfect", "Past perfect"],
    educationLevels: ["matric", "intermediate", "graduation"],
    tags: ["english", "tenses"],
  },
  {
    stem: "Choose the passive voice of: 'Ali wrote the letter.'",
    subject: "english",
    topic: "active-passive-voice",
    difficulty: "MEDIUM",
    correct: 1,
    options: ["The letter is written by Ali.", "The letter was written by Ali.", "The letter has written Ali.", "The letter wrote Ali."],
    educationLevels: ["matric", "intermediate", "graduation"],
    tags: ["english", "voice"],
  },
  {
    stem: "Identify the noun in the sentence: 'Honesty is the best policy.'",
    subject: "english",
    topic: "parts-of-speech",
    difficulty: "EASY",
    correct: 3,
    options: ["is", "the", "best", "Honesty"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["english", "grammar"],
  },
  {
    stem: "What is 25% of 200?",
    subject: "mathematics",
    topic: "percentages",
    difficulty: "EASY",
    correct: 2,
    options: ["25", "40", "50", "75"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["mathematics", "percentage"],
  },
  {
    stem: "What is the average of 10, 20 and 30?",
    subject: "mathematics",
    topic: "averages",
    difficulty: "EASY",
    correct: 1,
    options: ["15", "20", "25", "30"],
    educationLevels: ["middle", "matric"],
    tags: ["mathematics", "average"],
  },
  {
    stem: "If x + 7 = 15, what is x?",
    subject: "mathematics",
    topic: "algebra",
    difficulty: "EASY",
    correct: 2,
    options: ["6", "7", "8", "9"],
    educationLevels: ["middle", "matric"],
    tags: ["mathematics", "algebra"],
  },
  {
    stem: "What is the square of 12?",
    subject: "mathematics",
    topic: "arithmetic",
    difficulty: "EASY",
    correct: 2,
    options: ["124", "132", "144", "156"],
    educationLevels: ["middle", "matric"],
    tags: ["mathematics"],
  },
  {
    stem: "A ratio of 2:3 has a total of 25 parts. What is the value of the smaller share?",
    subject: "mathematics",
    topic: "percentages",
    difficulty: "MEDIUM",
    correct: 1,
    options: ["8", "10", "12", "15"],
    educationLevels: ["matric", "intermediate"],
    tags: ["mathematics", "ratio"],
  },
  {
    stem: "What is the perimeter of a square with side 6 cm?",
    subject: "mathematics",
    topic: "geometry",
    difficulty: "EASY",
    correct: 2,
    options: ["12 cm", "18 cm", "24 cm", "36 cm"],
    educationLevels: ["middle", "matric"],
    tags: ["mathematics", "geometry"],
  },
  {
    stem: "What is 3/4 expressed as a percentage?",
    subject: "mathematics",
    topic: "percentages",
    difficulty: "EASY",
    correct: 2,
    options: ["25%", "50%", "75%", "80%"],
    educationLevels: ["middle", "matric"],
    tags: ["mathematics", "fractions"],
  },
  {
    stem: "If a product costs Rs. 800 and is sold for Rs. 1,000, what is the profit?",
    subject: "mathematics",
    topic: "arithmetic",
    difficulty: "EASY",
    correct: 2,
    options: ["Rs. 100", "Rs. 150", "Rs. 200", "Rs. 250"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["mathematics", "profit"],
  },
  {
    stem: "What is the chemical symbol for oxygen?",
    subject: "general-science",
    topic: "chemistry",
    difficulty: "EASY",
    correct: 1,
    options: ["Ox", "O", "Og", "Om"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["science", "chemistry"],
  },
  {
    stem: "What gas do plants primarily use during photosynthesis?",
    subject: "general-science",
    topic: "biology",
    difficulty: "EASY",
    correct: 2,
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["science", "biology"],
  },
  {
    stem: "What is the basic unit of life?",
    subject: "general-science",
    topic: "biology",
    difficulty: "EASY",
    correct: 1,
    options: ["Tissue", "Cell", "Organ", "Atom"],
    educationLevels: ["middle", "matric"],
    tags: ["biology"],
  },
  {
    stem: "Which organ pumps blood throughout the human body?",
    subject: "general-science",
    topic: "human-body",
    difficulty: "EASY",
    correct: 1,
    options: ["Liver", "Heart", "Kidney", "Lung"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["biology", "human-body"],
  },
  {
    stem: "What is the SI unit of force?",
    subject: "general-science",
    topic: "physics",
    difficulty: "EASY",
    correct: 2,
    options: ["Joule", "Watt", "Newton", "Pascal"],
    educationLevels: ["matric", "intermediate"],
    tags: ["physics"],
  },
  {
    stem: "At approximately what temperature does pure water freeze at standard atmospheric pressure?",
    subject: "general-science",
    topic: "physics",
    difficulty: "EASY",
    correct: 0,
    options: ["0°C", "10°C", "50°C", "100°C"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["science"],
  },
  {
    stem: "Which particle has a negative electric charge?",
    subject: "general-science",
    topic: "physics",
    difficulty: "EASY",
    correct: 2,
    options: ["Proton", "Neutron", "Electron", "Nucleus"],
    educationLevels: ["matric", "intermediate"],
    tags: ["physics", "atoms"],
  },
  {
    stem: "What does CPU stand for?",
    subject: "computer",
    topic: "computer-fundamentals",
    difficulty: "EASY",
    correct: 0,
    options: ["Central Processing Unit", "Computer Processing Utility", "Central Program Utility", "Computer Primary Unit"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["computer", "cpu"],
  },
  {
    stem: "Which device is primarily used to enter text into a computer?",
    subject: "computer",
    topic: "hardware",
    difficulty: "EASY",
    correct: 1,
    options: ["Monitor", "Keyboard", "Speaker", "Printer"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["computer", "hardware"],
  },
  {
    stem: "Which of the following is an operating system?",
    subject: "computer",
    topic: "software",
    difficulty: "EASY",
    correct: 0,
    options: ["Linux", "HTML", "JPEG", "USB"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["computer", "software"],
  },
  {
    stem: "What does URL stand for?",
    subject: "computer",
    topic: "networking",
    difficulty: "EASY",
    correct: 1,
    options: ["Universal Record Link", "Uniform Resource Locator", "Unified Routing Link", "User Resource Location"],
    educationLevels: ["matric", "intermediate", "graduation"],
    tags: ["computer", "internet"],
  },
  {
    stem: "Which application is commonly used to create spreadsheets?",
    subject: "computer",
    topic: "ms-office",
    difficulty: "EASY",
    correct: 1,
    options: ["Microsoft Word", "Microsoft Excel", "Microsoft Paint", "Notepad"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["computer", "ms-office"],
  },
  {
    stem: "Pakistan came into existence on which date?",
    subject: "pakistan-studies",
    topic: "pakistan-movement",
    difficulty: "EASY",
    correct: 1,
    options: ["23 March 1940", "14 August 1947", "11 September 1948", "25 December 1947"],
    educationLevels: ["primary", "middle", "matric", "intermediate"],
    tags: ["pakistan", "history"],
  },
  {
    stem: "Who was the founder of Pakistan?",
    subject: "pakistan-studies",
    topic: "pakistan-movement",
    difficulty: "EASY",
    correct: 1,
    options: ["Allama Iqbal", "Muhammad Ali Jinnah", "Liaquat Ali Khan", "Sir Syed Ahmad Khan"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["pakistan", "history"],
  },
  {
    stem: "What is the capital city of Pakistan?",
    subject: "pakistan-studies",
    topic: "pakistan-geography",
    difficulty: "EASY",
    correct: 2,
    options: ["Lahore", "Karachi", "Islamabad", "Peshawar"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["pakistan", "geography"],
  },
  {
    stem: "Which is the largest province of Pakistan by area?",
    subject: "pakistan-studies",
    topic: "pakistan-geography",
    difficulty: "EASY",
    correct: 2,
    options: ["Punjab", "Sindh", "Balochistan", "Khyber Pakhtunkhwa"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["pakistan", "geography"],
  },
  {
    stem: "What is the national language of Pakistan?",
    subject: "pakistan-studies",
    topic: "national-symbols",
    difficulty: "EASY",
    correct: 1,
    options: ["Punjabi", "Urdu", "Sindhi", "English"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["pakistan"],
  },
  {
    stem: "How many obligatory prayers are there in Islam each day?",
    subject: "islamiat",
    topic: "ibadat",
    difficulty: "EASY",
    correct: 2,
    options: ["Three", "Four", "Five", "Six"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["islamiat", "prayer"],
  },
  {
    stem: "Which month of the Islamic calendar is associated with fasting?",
    subject: "islamiat",
    topic: "ibadat",
    difficulty: "EASY",
    correct: 2,
    options: ["Muharram", "Rajab", "Ramadan", "Shawwal"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["islamiat", "fasting"],
  },
  {
    stem: "What is the first month of the Islamic calendar?",
    subject: "islamiat",
    topic: "islamic-history",
    difficulty: "EASY",
    correct: 0,
    options: ["Muharram", "Ramadan", "Shawwal", "Safar"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["islamiat"],
  },
  {
    stem: "What is the obligatory charity in Islam commonly called?",
    subject: "islamiat",
    topic: "ibadat",
    difficulty: "EASY",
    correct: 1,
    options: ["Sawm", "Zakat", "Hajj", "Salah"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["islamiat", "zakat"],
  },
  {
    stem: "Which is the largest ocean on Earth?",
    subject: "general-knowledge",
    topic: "world-geography",
    difficulty: "EASY",
    correct: 2,
    options: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["general-knowledge", "geography"],
  },
  {
    stem: "Which planet is known as the Red Planet?",
    subject: "general-knowledge",
    topic: "inventions-discoveries",
    difficulty: "EASY",
    correct: 1,
    options: ["Venus", "Mars", "Jupiter", "Mercury"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["general-knowledge", "space"],
  },
  {
    stem: "Which instrument is used to measure temperature?",
    subject: "general-knowledge",
    topic: "inventions-discoveries",
    difficulty: "EASY",
    correct: 1,
    options: ["Barometer", "Thermometer", "Ammeter", "Hygrometer"],
    educationLevels: ["primary", "middle", "matric"],
    tags: ["general-knowledge", "science"],
  },
  {
    stem: "Which instrument is used to measure atmospheric pressure?",
    subject: "everyday-science",
    topic: "scientific-instruments",
    difficulty: "EASY",
    correct: 1,
    options: ["Thermometer", "Barometer", "Ammeter", "Voltmeter"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["science", "instruments"],
  },
  {
    stem: "What is the SI unit of electric current?",
    subject: "everyday-science",
    topic: "units-measurements",
    difficulty: "EASY",
    correct: 2,
    options: ["Volt", "Ohm", "Ampere", "Watt"],
    educationLevels: ["matric", "intermediate"],
    tags: ["science", "units"],
  },
  {
    stem: "Find the next number: 2, 4, 6, 8, ?",
    subject: "analytical-reasoning",
    topic: "series-sequences",
    difficulty: "EASY",
    correct: 1,
    options: ["9", "10", "11", "12"],
    educationLevels: ["middle", "matric", "intermediate"],
    tags: ["reasoning", "series"],
  },
  {
    stem: "Find the next number: 3, 6, 12, 24, ?",
    subject: "analytical-reasoning",
    topic: "series-sequences",
    difficulty: "MEDIUM",
    correct: 2,
    options: ["36", "42", "48", "54"],
    educationLevels: ["matric", "intermediate", "graduation"],
    tags: ["reasoning", "series"],
  },
  {
    stem: "Which one is different from the others?",
    subject: "analytical-reasoning",
    topic: "odd-one-out",
    difficulty: "EASY",
    correct: 2,
    options: ["Mango", "Banana", "Apple", "Carrot"],
    educationLevels: ["primary", "middle"],
    tags: ["reasoning"],
  },];

/**
 * Materialise the curated bank into SeedQuestions, deriving a stable slug from
 * the stem and leaving exam links to be resolved by subject (as the generators
 * do). Curated items are marked as verified practice since they are hand-checked.
 */
export function generateCuratedQuestions(): SeedQuestion[] {
  const seen = new Set<string>();
  const out: SeedQuestion[] = [];

  for (const item of BANK) {
    const slug = curatedSlug(item.stem);
    if (seen.has(slug)) continue;
    seen.add(slug);
    out.push({
      ...item,
      slug,
      exams: [],
      status: "PUBLISHED",
      origin: "VERIFIED_PRACTICE",
      source: "Original practice question",
    });
  }

  return out;
}

function curatedSlug(stem: string): string {
  const base = stem
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return `curated-${base}`;
}
